# Generated by Django 4.1.3 on 2022-12-01 14:19

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('Firm Fixed Price', 'Firm Fixed Price'), ('Fixed Price Incentive', 'Fixed Price Incentive'), ('Time and Materials', 'Time And Materials'), ('Cost Plus Fixed Fee', 'Cost Plus Fixed Fee'), ('Cost Plus Incentive Fees', 'Cost Plus Incentive Fees'), ('Cost Plus Award Fee', 'Cost Plus Award Fee')], default='Firm Fixed Price', max_length=50)),
                ('contract_status', models.CharField(choices=[('Active', 'Active'), ('Awarded', 'Awarded'), ('Closed', 'Closed'), ('Draft', 'Draft'), ('In progress', 'In Progress'), ('New', 'New'), ('Not Awarded', 'Not Awarded'), ('Pending', 'Pending')], default='Active', max_length=50)),
                ('tag_type', models.CharField(choices=[('Cohorts', 'Cohorts'), ('Colleges', 'Colleges'), ('Education', 'Education'), ('Government', 'Government'), ('IT', 'It'), ('Non Profits', 'Non Profits'), ('Private Consumer', 'Private Clint'), ('Public Health', 'Public Health'), ('Universities', 'Universities'), ('Other', 'Other')], default='Government', max_length=50)),
                ('title', models.CharField(default='IHRC -', max_length=100)),
                ('company_name', models.CharField(default='IHRC INC.', max_length=100)),
                ('contract_number', models.CharField(default='000-000-0000-YYYY', max_length=100)),
                ('office', models.CharField(blank=True, default='Atlanta', max_length=100, null=True)),
                ('division', models.CharField(blank=True, default='CORPORATE ', max_length=100, null=True)),
                ('short_description', ckeditor.fields.RichTextField(blank=True, default='The short description is  ', null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('prime', models.CharField(blank=True, max_length=100, null=True)),
                ('prime_pm', models.CharField(blank=True, max_length=100, null=True)),
                ('sub', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_pm', models.CharField(blank=True, max_length=100, null=True)),
                ('current_year', models.CharField(blank=True, default='Option Year 1 ', max_length=100, null=True)),
                ('total_funding', models.FloatField(blank=True, null=True)),
                ('current_funding', models.FloatField(blank=True, null=True)),
                ('funded', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='Atlanta', max_length=100)),
                ('state', models.CharField(blank=True, default='Georgia', max_length=100)),
                ('zipcode', models.CharField(blank=True, default='30082', max_length=100)),
                ('contact_email', models.CharField(blank=True, default='first_name@ihrc.com', max_length=50)),
                ('contract_award', models.FileField(blank=True, null=True, upload_to='contract-docs/')),
                ('contract_amendment', models.FileField(blank=True, null=True, upload_to='contract-docs/')),
                ('contract_renewal', models.FileField(blank=True, null=True, upload_to='contract-docs/')),
                ('contract_nda', models.FileField(blank=True, null=True, upload_to='contract-docs/')),
                ('main_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 1, 9, 19, 59, 191971))),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
    ]
