# Generated by Django 4.1.3 on 2022-12-02 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_contracts_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 1, 20, 36, 19, 334547)),
        ),
    ]
