# Generated by Django 4.1.3 on 2022-12-02 17:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0008_alter_contracts_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 24, 57, 978518)),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Amendment', 'Amendment'), ('Award', 'Award'), ('Contractor Performance Assessment Reporting System', 'Cpars'), ('Deliverables', 'Deliverables'), ('Draft', 'Draft'), ('Modifications', 'Mods'), ('Non Disclosure Agreement', 'Nda'), ('New', 'New'), ('Progress Report', 'Progressreport'), ('Renewal', 'Renewal'), ('Sub-Contract Agreement', 'Subcontract')], default='Draft', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('Cohorts', 'Cohorts'), ('Colleges', 'Colleges'), ('Education', 'Education'), ('Government', 'Government'), ('IT', 'It'), ('Non Profits', 'Non Profits'), ('Private Consumer', 'Private Clint'), ('Public Health', 'Public Health'), ('Universities', 'Universities'), ('Other', 'Other')], default='Government', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('attach_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
