# Generated by Django 4.1.3 on 2022-12-02 17:43

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0012_alter_contracts_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sins_proposed', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('educational_level', models.CharField(blank=True, max_length=100, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('price_year_1', models.FloatField(blank=True, null=True)),
                ('price_year_2', models.FloatField(blank=True, null=True)),
                ('price_year_3', models.FloatField(blank=True, null=True)),
                ('price_year_4', models.FloatField(blank=True, null=True)),
                ('price_year_5', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 43, 29, 223927))),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LaborPosition',
                'verbose_name_plural': 'LaborPositions',
            },
        ),
        migrations.AlterField(
            model_name='contracts',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 43, 29, 222929)),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last')),
                ('first_name', models.CharField(max_length=64, verbose_name='First')),
                ('middle_name', models.CharField(max_length=64, verbose_name='Middle')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 43, 29, 223927))),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='ClinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(blank=True, max_length=10, null=True)),
                ('supplies_services_description', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('Ea', 'Each'), ('Lot', 'Lot'), ('Job', 'Job'), ('Other', 'Other')], default='Ea', max_length=10)),
                ('unit_price', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('option_year', models.CharField(choices=[('0', 'Base Period'), ('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6'), ('7', 'Year 7'), ('8', 'Year 8'), ('9', 'Year 9'), ('10', 'Year 10')], default='0', max_length=10)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_time', models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 43, 29, 224922))),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('contracts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contracts')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ClinReport',
                'verbose_name_plural': 'ClinReports',
            },
        ),
    ]
