# Generated by Django 4.1.3 on 2022-12-02 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_laborposition_alter_contracts_created_time_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinreport',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 48, 27, 387964)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 48, 27, 385971)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 48, 27, 387964)),
        ),
        migrations.AlterField(
            model_name='laborposition',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 2, 12, 48, 27, 387964)),
        ),
    ]
