# Generated by Django 4.1.3 on 2022-12-05 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_alter_clinreport_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinreport',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 5, 8, 12, 27, 39279)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 5, 8, 12, 27, 37279)),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='effective_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='renewal_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 5, 8, 12, 27, 39279)),
        ),
        migrations.AlterField(
            model_name='laborposition',
            name='created_time',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 12, 5, 8, 12, 27, 39279)),
        ),
    ]
